@startuml
' class Animal <<Abstract>> {
' ---
' + Walk:void
' + {abstract} eat():int
' + {abstract} cry():void
' }
' class Dog {
' ---
' + eat():int
' + cry():void
' }
' class Cat {
' ---
' + eat():int
' + cry():void
' }
' Animal <|-down- Dog
' Animal <|-down- Cat
class Word {
---
+ enter():void
}
class Excel {
---
+ enter():void
}
interface keyboard {
' <<interface>>
---
+ enter():void
}
keyboard <|.. Word
keyboard <|.. Excel
class User {
}
keyboard <-up- User:<< use >>

@enduml