@startuml
' skinparam classAttributeIconSize 0
class 空車リスト {
- 管理番号:String

}
class 車 {
- 管理番号:int  
- 車種:String 
- 駆動方式:String  
}
class 顧客 {
- 顧客ID:String
- 氏名:String
- 電話番号:String
- 郵便番号:String
- 住所:String
---
+ setName(氏名:String) void
}
class 予約 {
- 予約番号:String
- 管理番号:String 
- 顧客ID:String 
- 予約日:String
}

class 貸し出し {
- 貸し出し番号:String 
- 管理番号:String 
- 顧客ID:String 
- 予約日:String

}
hide 空車リスト circle
hide 車 circle
hide 顧客 circle
hide 予約 circle
hide 貸し出し circle

@enduml