@startuml オブジェクト図
    left to right direction
    object "<u>車一覧:車</u>" as car1{
        車種
    }
    object "<u>車一覧:車</u>" as car2{
        車種
    }
    object "<u>タイヤ一覧:タイヤ</u>" as tire1{
        種類=オールシーズンタイヤ
        メーカー
        サイズ
        価格
    }
    object "<u>タイヤ一覧:タイヤ</u>" as tire2{
        種類=スタッドレスタイヤ
        メーカー
        サイズ
        価格
    }
    car1 -- tire1
    car1 -- tire2
    car2 -- tire1
@enduml