@startuml ステート
' left to right direction
[*] -right-> メニュー
メニュー -right-> [*]
予約と確認-->メニュー :取消ボタン
予約と確認-right->あなたの順番 :確認ボタン
予約と確認-right-->あなたの順番 :登録ボタン
メニュー-->予約と確認 :予約と確認ボタン
メニュー<--今の順番 :メニューボタン
メニュー<--あなたの順番 :メニューボタン
メニュー-->今の順番 :今の順番ボタン
@enduml